root: ./docs

structure:
  readme: en/README.md
  summary: en/SUMMARY.md

variants:
  - name: English
    path: ./en
    default: true
  - name: Español
    path: ./es
  - name: Português
    path: ./pt

plugins:
  - search
  - sharing
  - fontsettings
  - theme-default

pluginsConfig:
  search:
    maxIndexSize: 1000000
  sharing:
    facebook: true
    twitter: true
    google: true
    linkedin: true
    all: ["facebook", "google", "twitter", "linkedin"]